name: Makefile CI

on:
  push:
  pull_request:
  schedule:
      - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Run check
      run: |
        make clean
        make check --debug=a SHELL='sh -xvp'

    - name: Run test
      run: |
        make clean
        make test --debug=a SHELL='sh -xvp'

    - name: Run staged install and uninstall
      run: |
        make clean
        make install DESTDIR=.make PREFIX=local
        make uninstall DESTDIR=.make PREFIX=local

    - name: Run install and uninstall
      run: |
        make clean
        make install
        make uninstall
